// import { useContext } from 'react';
import Head from 'next/head';
import Link from 'next/link';

import { dehydrate, QueryClient } from '@tanstack/react-query';
import { getBasketsQuery } from '@/lib/api-functions/server/baskets/queries';
import { STORAGE_KEY } from '@/lib/tq/baskets/settings';

import { log } from '@/lib/utils/formatters';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import QueryBoundaries from '@/components/QueryBoundaries';
import BasketList from '@/components/BasketList';
import { Button } from '@mui/material';

import { useDelete } from '@/lib/tq/baskets/mutations';
// import { UIContext } from '@/components/contexts/UI.context';

export default function AdminBasketList() {
  const removeMutation = useDelete();

  const removeHandler = (id) => {
    removeMutation.mutate(id);
  };
  return (
    <>
      <Head>
        <title>My Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Baskets</Heading>
        <Button
          variant="contained"
          component={Link}
          href={`/admin/baskets/add`}
        >
          Add Basket
        </Button>
        <QueryBoundaries>
          <BasketList />
        </QueryBoundaries>
      </Layout>
    </>
  );
}

export async function getStaticProps(context) {
  // console.log("LLLL", context);
  const baskets = await getBasketsQuery().catch((err) => console.log(err));
  const queryClient = new QueryClient();

  // If this was remote we'd use 'prefetchQuery' but as we know it we use 'setQueryData'
  await queryClient.setQueryData(
    [STORAGE_KEY],
    JSON.parse(JSON.stringify(baskets)),
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
