import Head from 'next/head';
// import Image from 'next/image';
// import { Inter } from 'next/font/google';
import { Button, AirIcon, EditCalendarIcon } from '@/components/mui';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Paragraph from '@/components/Paragraph';
// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">
          Home Page
        </Heading>
        <Paragraph>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius
          repudiandae saepe iusto nihil autem, hic necessitatibus repellendus
          reiciendis consequuntur adipisci explicabo et eveniet aperiam repellat
          corporis? Molestias nihil sapiente id?
        </Paragraph>
        <Button variant="contained">
          <EditCalendarIcon />
          Button
        </Button>
      </Layout>
    </>
  );
}
